const path = require("path");

const SOURCE_NAMES = [
  "blank",
  "react",
  "vue",
  "svelte",
  "preact",
  "lit-element",
];
const SOURCE_PATHS = new Map();

for (const template of SOURCE_NAMES) {
  SOURCE_PATHS.set(template, path.join(__dirname, template));
  SOURCE_PATHS.set(
    `${template}-typescript`, path.join(__dirname, `${template}-typescript`)
  );
}

const SOURCE_CONFIGS = new Map(Object.entries({
  blank: {
    baseTemplate: "blank",
    typescript: false,
    testing: "",
    codeFormatters: ["prettier"],
    sass: false,
    cssFramework: null,
    bundler: null,
    plugins: [],
    license: "mit",
  },
  "blank-typescript": {
    baseTemplate: "blank",
    typescript: true,
    testing: "",
    codeFormatters: ["prettier"],
    sass: false,
    cssFramework: null,
    bundler: null,
    plugins: [],
    license: "mit",
  },
  react: {
    baseTemplate: "react",
    typescript: false,
    testing: "wtr",
    codeFormatters: ["prettier"],
    sass: false,
    cssFramework: null,
    bundler: null,
    plugins: [],
    license: "mit",
  },
  "react-typescript": {
    baseTemplate: "react",
    typescript: true,
    testing: "wtr",
    codeFormatters: ["prettier"],
    sass: false,
    cssFramework: null,
    bundler: null,
    plugins: [],
    license: "mit",
  },
  vue: {
    baseTemplate: "vue",
    typescript: false,
    testing: "",
    codeFormatters: [],
    sass: false,
    cssFramework: null,
    bundler: null,
    plugins: [],
    license: "mit",
  },
  "vue-typescript": {
    baseTemplate: "vue",
    typescript: true,
    testing: "",
    codeFormatters: [],
    sass: false,
    cssFramework: null,
    bundler: null,
    plugins: [],
    license: "mit",
  },
  svelte: {
    baseTemplate: "svelte",
    typescript: false,
    testing: "wtr",
    codeFormatters: [],
    sass: false,
    cssFramework: null,
    bundler: null,
    plugins: [],
    license: "mit",
  },
  "svelte-typescript": {
    baseTemplate: "svelte",
    typescript: true,
    testing: "wtr",
    codeFormatters: [],
    sass: false,
    cssFramework: null,
    bundler: null,
    plugins: [],
    license: "mit",
  },
  preact: {
    baseTemplate: "preact",
    typescript: false,
    testing: "wtr",
    codeFormatters: ["prettier"],
    sass: false,
    cssFramework: null,
    bundler: null,
    plugins: [],
    license: "mit",
  },
  "preact-typescript": {
    baseTemplate: "preact",
    typescript: true,
    testing: "wtr",
    codeFormatters: ["prettier"],
    sass: false,
    cssFramework: null,
    bundler: null,
    plugins: [],
    license: "mit",
  },
  "lit-element": {
    baseTemplate: "lit-element",
    typescript: false,
    testing: "",
    codeFormatters: ["prettier"],
    sass: false,
    cssFramework: null,
    bundler: null,
    plugins: [],
    license: "mit",
  },
  "lit-element-typescript": {
    baseTemplate: "lit-element",
    typescript: true,
    testing: "",
    codeFormatters: ["prettier"],
    sass: false,
    cssFramework: null,
    bundler: null,
    plugins: [],
    license: "mit",
  },
}));

module.exports = {
  SOURCE_NAMES,
  SOURCE_PATHS,
  SOURCE_CONFIGS,
};
